### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by fabienheureux** [Kikobeats/cacheable-response#11]
Hey, I went through the docs and am not sure about how it handles language in request.
Does the cache invalidate if language in the  request changes? 

I have a nextjs app running with i18next and ssr got pretty buggy when I try to use cacheable-response.

Thanks a lot for tour work by the way, docs are very well written and the package itself is very easy to use.

**Comment by Kikobeats** [comment]
Hey fabie! thanks for your words 🙂

I'm not using multilanguage in my user case, so I didn't implement the library for support that.

However, we can add it. How this is normally done?

I suppose the client needs to send a request header with the i18n, then the server tries to find or cache a specific translation response for that.

Can we find any reference that defines how this can be implemented?

**Comment by dimensi** [comment]
The package uses req.url as the key, and next.js also as the path req.url. For example, there is a package for next.js next-i18next, where it cuts out the req.url subpath in which the language is enclosed https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.js#L53.
I solved this problem by giving your package a path with the language, and nextjs without the language.

```js
const ssrCache = cacheableResponse({
  ttl: hoursToMs(6),
  get: async ({ req, res, pagePath, queryParams }) => ({
    data: await app.renderToHTML(req, res, pagePath, queryParams),
  }),
  send: ({ data, res }) => res.send(data),
})

  server.get('*', (req, res) => {
    if (req.url.includes('_next/') || req.url.includes('static/')) {
      return handle(req, res)
    }

    const pagePath = req.url
    req.url = req.originalUrl
    return ssrCache({ req, res, pagePath })
  })
```
I suggest that in order to avoid such problems in the future, it is possible to add the key directly, if the key is not thrown then use req.url
```js
ssrCache({ req, res, key, pagePath })
```
Looking at the design of your package, I see that we cannot generate the key inside the get() function. That's why I see only this solution.

**Comment by Kikobeats** [comment]
@dimensi @fabienheureux can you take a look to https://github.com/Kikobeats/cacheable-response/issues/22? I think it's strongly related since both things are trying to do the same: differentiate cache storage instances using more things that the query parameters passed.
