### ISSUE TITLE
Opting out of cache for authenticated requests

### ISSUE THREAD

**Issue by brad-decker** [Kikobeats/cacheable-response#6]
Greetings,

This issue is totally a question and not really an issue with the project. I came here from https://github.com/zeit/next.js/pull/6393 and I am intrigued by the Cloudflare/caching strategy here. I am curious of a number of things:

1. If using a CDN for distributed cache, what purpose does the keyv/in memory store serve on the server instance? 
2. We currently have a few parts of each page that indicate the currently logged in user, but a majority of the page is the same content that a non-authenticated user would see. At present we are not caching any pages for users who are authenticated. Do you have any suggestions for dealing with this particular issue, either best practices for how to bypass the caching mechanism or a way to cache these pages as well safely? I also imagine a CDN would further complicate this issue?
3. The cache control headers and etags allow the client's browser to cache the content, correct? Does setting these values allow the client to bypass the server request altogether for pages they have visited in the past up until the expiry?

I may have more questions. Appreciate the work you've done and looking forward to using this library in our next.js project.

**Comment by Kikobeats** [comment]
1) Because two cache layers are better than one 😛
2) Probably you need to choose between cache or not; looks like partial caching for views would be potentially difficult to maintain and debug. Also, keep in mind caching is not something you can't always do (for example, real time apps should be real time)
3) I think your question is related with [Last-Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified). As I understand, this feature should be implemented on browser level; Etag provides the surface for doing that.
