### ISSUE TITLE
Allow to bypass .send on a cache miss

### ISSUE THREAD

**Issue by cascandaliato** [Kikobeats/cacheable-response#63]
Next.js example [`ssr-caching`](https://github.com/vercel/next.js/tree/canary/examples/ssr-caching) is currently broken (vercel/next.js#16372, vercel/next.js#16725) because there is no way to have Next.js ssr-render the page content on a cache miss without it also writing and `.end`-ing the response. Previous versions of the example relied on `app.renderToHTML` which has been deprecated because it's an internal API (vercel/next.js#14737).

I suggest we add a flag to bypass the `.send()` in `cacheable-response` when a cache miss happens, for those cases where the framework takes care of the `req`/`res` lifecycle till the end. We can add it either as an option in `cacheableResponse({})` or as a property of `.get()`'s return value.

**Comment by Kikobeats** [comment]
Hey, although some people used cacheable-response in the past with Next.js, just I warn about the fact cacheable-response is a general-purpose library rather than a specific Next.js solution.

Saying that I feel cacheable-response as general-purpose library should handle the response properly. If Next.js should skip sending function under determinate situations, then the library should provide the basics primitives for doing that.

> I suggest we add a flag to bypass the .send() in cacheable-response when a cache miss happens

so correct if I am wrong (mainly because I'm not using Next.js with cacheable-response), just passing `isHit` to `send` will resolve the issue?

Can you promote this into a PR? 🙂

**Comment by cascandaliato** [comment]
Sorry, I should have been more accurate in my proposal:
- when we call Next.js to render the page (and pass the result back to the library), we cannot stop Next.js from `.send`/`.end`-ing the response on its own;
- if we send a result back to the library (because we want the library to cache it), then the library tries to set headers, send the response, etc. and this makes the server complain because the request has already been answered by Next.js;
https://github.com/Kikobeats/cacheable-response/blob/ef2214af84ca994cd969de78ab1f0e3814a35ace/index.js#L106
- I suggest we add an option to make the library skip the `.setHeaders`/`.end`/`.send` parts when `isHit === false`.
![image](https://user-images.githubusercontent.com/8927157/99691544-a3af6880-2a89-11eb-99bb-ba9e661d2bfd.png)

If this enhancement makes sense to you, I'll work on a PR.

**Comment by Kikobeats** [comment]
I think this is closely related to https://github.com/Kikobeats/cacheable-response/issues/64#issuecomment-770854230

I want to make this library Next.js friendly, but keeping in mind this is not a Next.js specific solution.

Said that, I'm very welcome to accept a PR doing the library easy to connect if the current functionality keeps the same.
