### ISSUE TITLE
How to flush cache at background after every request ?

### ISSUE THREAD

**Issue by Huai-Kang** [Kikobeats/cacheable-response#73]
Hi, I notice that by adding `?force=true` to flush cache, so how about flush cache at background after every request(do the same thing without force param) ?

Just like [SWR](https://swr.vercel.app/), through constant request to flush cache all the time, I think this can always return fresh cache to browser.

**Comment by Kikobeats** [comment]
The `force=true` is just a way to forcing fresh copy under specific situations (like debugging).

If you want to use flush cache all the time... maybe don't use `cacheable-response`?
  
I don't understand the use case for this. Also, I don't follow SWR comparison since it is not caching, just polling.

**Comment by Kikobeats** [comment]
closing since it is not actually an issue, but please feel free to reply, happy to continue the conversation 🙂
